### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ehb54** [pjzuk/GRPY#1]
We would like to include the executable for this code within US-SOMO.
http://somo.aucsolutions.com/
Can we have permission to include the code with appropriate accreditation?

Best regards.

**Comment by pjzuk** [comment]
Hi,
in principle GRPY is GNU General Public License v3 as stated in userGuide.pdf. In case of PLASMA version please refer to their license policy. There is also a synthetic list of what we would be very grateful if you acknowledge scince-wise. I really appreciate your work on US-SOMO.
best regards,
Pawel

**Comment by ehb54** [comment]
Hi Pawel,

Thanks for the clarification. The README's simply state  "Copyright (C) 2017 Pawel Jan Zuk", which motivated my raising the issue. Now, I dug a bit further and see the code itself includes the GPL v3. I think we are fine to distribute. We will, of course, properly acknowledge GRPY in our user interface. 

Best regards,
Emre
