### ISSUE TITLE
Progress updates / memory check

### ISSUE THREAD

**Issue by ehb54** [pjzuk/GRPY#2]
Hi Pawel,

Would it be possible for you to add a progress update output to GRPY in both the serial and parallel versions? We have it working under US-SOMO (release soon), but it would be helpful to the users to get a live % complete progress update. Perhaps this is best as a command line option.

If necessary, I could dig into the code and create a pull request, but I think it might be faster for someone more familiar with the code to implement.

Best regards,
Emre.

**Comment by pjzuk** [comment]
Hi Emre,

if it will helps, I could try. I suppose you have something specific in mind right?

best regards,

Pawel

**Comment by ehb54** [comment]
I was thinking if there is an identifiable outer loop, one could output "this-count of max-count" or "x%" (each time on a new line - putting it on a new line makes it easier to grab the output on my side) .
Thoughts:
1. Keep it as simple as possible to not cause slowdown
2. it doesn't have to be linear in time, just to give the user an idea of progress
3. Output frequency might need throttling, i.e. if updates happen 1000 times per second, that would be a waste of output time. In these cases I would only output every 2000 counts or more (e.g. nice to have output every second or few, but even 30 seconds or more is tolerable).

Let me know if you have further questions or thoughts.

Best regards,
Emre

**Comment by pjzuk** [comment]
In general there are two major tasks there
1) creating matrices - here it is quite easy to identify a progress
2) inverting matrices - standard libraries like lapack are responsible. 

I think I could make an indicator what current task the code is performing. Would it be sufficient? Or % are better? 
Also, do you know a good (standard) library supporting indicator bars for fortran or is it better to do simple I/O commands? I am not most up to date with this matter.

best regards,
Pawel

**Comment by ehb54** [comment]
Simple I/O would be better for US-SOMO's needs (easy to parse for adding to the GUI).
A visual progress bar e.g. [===---------------] 18%
would also be doable, but for the general user, you probably want to keep it on one line (without the line feed).

best regards,
-e.

**Comment by ehb54** [comment]
The lapack matrix operations might just have to be a long time without progress updates.
 
best,
-e.

**Comment by pjzuk** [comment]
That being said. I will try to add it early next week. So if you have any more specific ideas we could wrap up till the end of next week.  All right?
best,
Pawel

**Comment by ehb54** [comment]
Yes, next week is more than fine. 
Thank you very much for your help with this. 

best,
Emre.
