### ISSUE TITLE
NaN results with test model.

### ISSUE THREAD

**Issue by ehb54** [pjzuk/GRPY#4]
Hi Pawel,

We have run across a test model with gives some NaN results.
```
 Rotational relaxation times associated with
               the Brownian relaxation of a traceless symmetric tensor:
                                                -> Relaxation time (1):        NaN [s]
                                                -> Relaxation time (2):        NaN [s]
                                                -> Relaxation time (3):  8.942E-12 [s]
                                                -> Relaxation time (4):  8.942E-12 [s]
                                                -> Relaxation time (5):  8.942E-12 [s]
                                      Harmonic mean (correlation) time:        NaN [s]
```

This result was duplicated on both Linux & OSX versions.
On OSX an additional informational message was produced:
`Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL`

Here is the GRPY format model:
```
P6_A                            Title
20                              Temperature
0.0100194                       Solvent viscosity
1                               Molecular weight
1                               Specific volume of macromolecule
0.998234                        Solution Density
1.E-8                           Unit of length for coordinates and radii, cm
6                               Number of beads
0.0000  0.0000  -1.4142 1.0000
0.0000  1.4142  0.0000  1.0000
1.4142  0.0000  0.0000  1.0000
-1.4142 0.0000  0.0000  1.0000
0.0000  -1.4142 0.0000  1.0000
0.0000  0.0000  1.4142  1.0000
```

Best regards,
Emre

**Comment by pjzuk** [comment]
WOW! I appreciate your testing routine!
It appears that in FORTRAN when you do SQRT(-8.1315162936412833E-020) you get NAN. I will add a check if what supposed to be zero is not a tiny negative number and all should be fine and uploaded tomorrow. Sorry for the trouble and thanks a ton!
best,
pawel

**Comment by pjzuk** [comment]
Hi Emre,
I have corrected that issue and uploaded to repository.
best,
pawel

**Comment by ehb54** [comment]
Hi Pawel,

Thanks for addressing this so quickly! 

Best regards,
Emre

**Comment by ehb54** [comment]
Hi Pawel,

I verify the fix worked on our tests. 

Thanks again,
Emre
